<a href="https://colab.research.google.com/github/tomkor96/data_scince_bootcamp/blob/main/wprowadzenie/algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Norma wektora, długość wektora w R2

In [2]:
import numpy as np
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1) # linalg - algebra liniowa
# norm - norma wektora tj. odległość od środka układu współrzędnych

4.123105625617661

Norma euklidesowa

In [ ]:
v2 = np.array([-10, 10, 13]) # przestrzeń trójwymiarowa
np.linalg.norm(v2) # odległość względem środka układu współrzędnych

19.209372712298546

Odległość dwóch punktów na płaszczyźnie

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

In [ ]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q) # odległość punktów od siebie w przestrzeni 3D

5.0990195135927845

Mnożenie macierzy - przydatne przy sieciach neuronowych i uczeniu maszynowym

In [ ]:
 X = np.array([[5, 3], [3, 9]]) # wymiar 2 x 2
 Y = np. array([[1], [-1]]) # wymair 2 x 1 - wiersze x kolumny

# mnożenie można wykonywać tylko wyedy, kiedy liczba kolumn lewej maierzy jest równa liczbie wierszy prawej macierzy
# macierz wynikowa będzie miała rozmiar wiersze lewej macierzy # kolumny prawej macierzy
# w tym przypadku 2 x 1

print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [ ]:
Z = np.dot(X, Y) # mnożenie macierzy
Z

array([[ 2],
       [-6]])

Wyznacznik macierzy - liczymy go tylko dla macierzy o równej liczbie wierszy i kolumn

In [ ]:
# macierz kwadratowa to taka macierz, której liczba wierszy = liczbie kolumn

In [ ]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A) wyznacznik macierzy

9.999999999999998

Ślad macierzy

In [ ]:
# suma elementów na przekątnej
np.trace(A)

5

Macierz jednostkowa

Macierz jednostkowa to specjalny rodzaj macierzy kwadratowej, która ma jedynki na głównej przekątnej (od lewego górnego do prawego dolnego rogu) i zera we wszystkich pozostałych miejscach. Oznaczana jako I


In [ ]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Macierz odwrotna

In [ ]:
# może być tylko kwadratowa
# AB = BA = I

In [ ]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [ ]:
np.set_printoptions(precision=4, suppress=True)
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transponowana - zamiana kolumny na wierze i wierszy na kolumny

In [ ]:
A

array([[ 2,  4],
       [-1,  3]])

In [ ]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

Rozwiązywanie układów równań

In [4]:
A = np.array([[2, 4], [1, -1]]) # macierz współczynników
A

array([[ 2,  4],
       [ 1, -1]])

In [5]:
B = np.array([[10], [-1]]) # macierz wyrazów wolnych, więcej info https://github.com/krakowiakpawel9/data-science-bootcamp/blob/84c700a7c6ebe1ed02dc0a103e0fd8b2cbfb28c1/01_wprowadzenie/02_algebra_liniowa.ipynb
B

array([[10],
       [-1]])

In [7]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X.shape

(2, 1)