<a href="https://colab.research.google.com/github/tomkor96/data_scince_bootcamp/blob/main/wprowadzenie/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Generowanie liczb pseudolosowych

In [1]:
import numpy as np

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn() # losowy rozkład normalny

0.4001572083672233

In [ ]:
x = np.random.randn(3, 4) # 10 losowo wygenerowanych liczb z rozkładu normalnego o średniej 0 i odchyleniu standardowym 1

In [ ]:
print('Średnia:', np.mean(x))
print('Odchylenie standardowe:', np.std(x))

Średnia: 0.44169134183476105
Odchylenie standardowe: 1.0156886561049374


In [ ]:
np.random.randn(10, 4)

array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656,  0.3869025 ]])

In [ ]:
np.random.rand() # losowa liczba lub liczby z przedziału <0, 1)

In [ ]:
np.random.randint(10) # liczba losowa mniejsza od 10, nieujemna

5

In [ ]:
np.random.randint(low=10, high=101, size=10)

array([68, 29, 74, 25, 64, 86, 11, 79, 40, 39])

In [ ]:
np.random.choice([4, 2, 1, 3])

4

In [ ]:
np.random.choice(['sql', 'python', 'java'])

'java'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)

In [ ]:
data

array([0, 1, 6, 7, 2, 3, 8, 4, 5, 9])

Podstawowe funkcje Numpy

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(9)

3.0

In [ ]:
np.all([2, 3, 1]) # jeżeli wszystkie wartości przekazanego obiektu iterowalnego mają wartość True, to zwraca True

True

In [ ]:
np.any([0, 0, 0]) # Jeżeli jakikolwiek obiekt iterowalny ma wartość True to zwraca True

False

In [ ]:
bool(1) # zwraca True dla każdej liczby różnej od 0

True

In [ ]:
A = np.random.rand(5)
A

array([0.84196967, 0.7372133 , 0.82380434, 0.08375847, 0.52107224])

In [ ]:
np.argmax(A) # indeks obiektu o najwyższej wartości w przekazanym obiekcie

0

In [ ]:
A[np.argmax(A)] # pokazanie wartości max

0.8419696664744106

In [ ]:
np.argmin(A)

3

In [ ]:
np.argsort(A)

array([3, 4, 1, 2, 0])

In [ ]:
np.max(A)

0.8419696664744106

In [ ]:
np.mean(A)

0.6015636027423945

In [ ]:
np.median(A)

0.737213298144971

In [ ]:
np.std(A)

0.2829091290696754

Indeksowanie i wycinanie tablic

In [3]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [ ]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[:2]

array([0, 1])

In [ ]:
A[[0, 2, 8]]

array([0, 2, 8])

In [ ]:
A[-1]

19

In [4]:
A = A.reshape(4, -1) # -1 to automatyczny dobór kolumn do podanej liczby wierszy
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[:, -1] # wycinanie kolumny

array([ 4,  9, 14, 19])

In [ ]:
A[0, 0] # = A[X][Y] X - indeks wiersza, Y - indeks kolumny

0

In [ ]:
A[1:3, 1:4] #  A[start_row:stop_row, start_column:stop_column]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [10]:
A[0:, 0] # wyświetle wszystkich elementów pierwszej kolumny

array([ 0,  5, 10, 15])

In [ ]:
A[1, 2] = 14

Iteracja po tablicach

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [ ]:
for item in A.flat:
  print(item)

Zmiana rozmiaru tablic

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A.shape

(4, 5)

In [ ]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
A.ravel() # wypłaszczenie dwuwymiarowej tablicy

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A.T # transponowanie - zamiana wierszy na kolumny

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [ ]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A[A > 0] # wyświetlenie tylko elementów > 0

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.bitwise_and(A > -5, A < 5) # bitwise - maski logiczne: and, or, xor, not

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
A[np.bitwise_and(A > -5, A < 5)] # wycinanie z użyciem maski

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
A[(A > -5) & (A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])